import {
    Error404Docs,
    AccordionDocs,
    AlertDocs,
    AvatarDocs,
    BadgeDocs,
    BannerDocs,
    BentoDocs,
    BlogListDocs,
    BottomNavigationDocs,
    BreadcrumbsDocs,
    ButtonDocs,
    CtaDocs,
    CardDocs,
    DividerDocs,
    DropdownDocs,
    FeaturesDocs,
    FooterDocs,
    HeroDocs,
    HeaderDocs,
    LoaderDocs,
    ModalDocs,
    PaginationDocs,
    SettingsDocs,
    SidebarDocs,
    SkeletonDocs,
    TabsDocs,
    TestimonialsDocs,
} from "@/app/docs/index";

export const components = {
    Error404: Error404Docs,
    Accordion: AccordionDocs,
    Alert: AlertDocs,
    Avatar: AvatarDocs,
    Badge: BadgeDocs,
    Banner: BannerDocs,
    Bento: BentoDocs,
    BlogList: BlogListDocs,
    BottomNavigation: BottomNavigationDocs,
    Breadcrumbs: BreadcrumbsDocs,
    Button: ButtonDocs,
    CTA: CtaDocs,
    Card: CardDocs,
    Divider: DividerDocs,
    Dropdown: DropdownDocs,
    Features: FeaturesDocs,
    Footer: FooterDocs,
    Hero: HeroDocs,
    Header: HeaderDocs,
    Loader: LoaderDocs,
    Modal: ModalDocs,
    Pagination: PaginationDocs,
    Settings: SettingsDocs,
    Sidebar: SidebarDocs,
    Skeleton: SkeletonDocs,
    Tabs: TabsDocs,
    Testimonials: TestimonialsDocs,
};